### ISSUE TITLE
Fix Selenium Web Driver Error

### ISSUE THREAD

**Issue by aydamacink** [sounddrop/sounddrop#77]
When running the complete tests we get 

```
Failure/Error: visit "/stats"
          Selenium::WebDriver::Error::WebDriverError:
            Could not find Firefox binary (os=macosx). Make sure Firefox is installed or set the path manually with Selenium::WebDriver::Firefox::Binary.path=

```

**Comment by langjoh** [comment]
Selenium is not compatible with Firefox 47 and later.

**Comment by langjoh** [comment]
We replaced Selenium with Capybara Web Kit, but some of the errors remain nonetheless. Carsten thinks the problem is Capybara in connection with the DataBase Cleaner, somehow the Cleaner does his job to early and erases the created factories, so in the end there's always a nil error.
So we will open a new issue, as the errors are not caused by Selenium anymore: #79
