### ISSUE TITLE
Let drops have lat/lng

### ISSUE THREAD

**Issue by carpodaster** [sounddrop/sounddrop#83]
Currently a `Drop` belongs to a `Place`  and the latter holds the geospatial data. With this setup, a Drop has to be created with a Place or mapped to one. Mapping a Drop to a Place is difficult and creating a Place alongsside a Drop will eventually result in many, many (duplicatee) places as it's very unlikely to exactly match a geolocation using the geolocation API of the client device.

I propose drops to hold their own geodata and remove the belongs_to association to Place. Instead a Drop should "belong" to a Place if it's in a Place's vicinity. "Vicinity" needs to be defined – is it 10, 50 or 100m?

The concept of a `Place` is not entirely clear to me. I would think of it as a well-known landmark, like e.g. the Berliner Dom. These places/sights could be imported (maybe there is open data for it or the Google Maps API gets us somewhere) but then again, Sounddrop should work globally and there are way too many sights to import.

**Comment by nynnejc** [comment]
The 'place' idea could be something inherited from the very first edition of the app, where there were barcode places in the SoundCloud office?

**Comment by berlintam** [comment]
so:
- move lat/long to drop
- remove place?
- create sort of.... virtual places/areas, that we define, & then associate a number of drops to that area once there are a few (like a 'kiez' model). OR create pre-determined places? Like the Berliner Dom & if there are drops close to that, associate them w/ the Berliner Dom?

I guess it all depends on what direction we want sounddrop to go in. I like the idea of giving users the freedom to create their own places (& be able to name them), because as an ex-writer & map enthusiast, I always thought of sounddrop as a place where I would, in the future, be able to create a walking tour or something. So my 'place' could be, for example, the gazebo on Richardplatz, the corkman graffiti art on the signpost at the corner of blah blah street etc.... These are all specific places, and part of the fun is going to exactly them & getting a sense of what the sounddroper was intending to create. 

I know @starkcoffee also had visions of using the app as a museum guide. So a place in her use case might be... the mona lisa, or... the guernica. You know? (maybe that helps to explain the concept of place a bit more). So in my mind, places have the potential to be very individualized, so personally, I'd like to keep them. I guess this would also speak against moving lat/long to drop, as drops are tied to their places (in this case, their coordinates).

That being said, I like the idea of having the ability to re-use places (or suggest nearby places). I also do not want the app filled with differently spelled versions of the berliner dom. Perhaps we can use the user's location data to display potential places near by & offer the user the possibility to use them if they want, that way we can cut down on duplicates. 

what do you think? @starkcoffee do you have any thoughts on this?

**Comment by carpodaster** [comment]
The semantics of a `Place` is much clearer to me now, thanks @nynnejc and @berlintam.

I still think that a drop should have their own lat/lng attributes. That way they can still relate to a place, but they can also exist "in the wild", i.e. without being forced to create a Place, and – like you said – potentially creating the 42nd instance of Berliner Dom.

**Comment by carpodaster** [comment]
I could work on a PR (leaving Place as it is, adding lat/lng to Drop, copying existing lat/lng data from places to their associated drops, relaxing validations for Drop) this weekend if that's ok?

**Comment by berlintam** [comment]
go for it! thanks @carpodaster. The idea of 'drops in the wild' is definitely growing on me :)

**Comment by berlintam** [comment]
@carpodaster this is sort of related https://github.com/sounddrop/sounddrop/issues/49

**Comment by langjoh** [comment]
@carpodaster I also think it is a good idea to make drops a bit less dependent on places.

**Comment by berlintam** [comment]
Closed via #89

**Comment by starkcoffee** [comment]
Hey sorry I'm late to this party, I need to review issues more. I'm not
sure about adding lat/long to Drop. Need to think more about it.

**Comment by starkcoffee** [comment]
Caught up with @berlintam about this. All good.
